### ISSUE TITLE
Casing of signature is an issue when signing with injected MetaMask provider.

### ISSUE THREAD

**Issue by GuiBibeau** [spruceid/siwe#143] opened 2023-01-19 15:48 UTC
### Description

When comparing a signature produced `with window.ethereum.request({ method: 'personal_sign, params: [message, address] })`, SiweMessage instance fails to compare because of address casing issues.

I receive this error message:

```
Error: Invalid signature.: 0xeE656Ff300be8B8867711139FE496b9790b8d4AE !== 0xee656ff300be8b8867711139fe496b9790b8d4ae
```

Here is where the error happens: [Link to PR showing error](https://github.com/MetaMask/examples/pull/4/files#diff-9efaeda09892a60c8d7cb8a0b8f3ee861a953ce1a29718216d661507bde62cc7R17)

Here is the message being signed without any ethereum convenience library and using the vanilla MetaMask methods:
[Link to PR showing error](https://github.com/MetaMask/examples/pull/4/files#diff-7c007f27b664eb3da50a02a65797a7418498782aa47eb49431e3c513e957eec5R63)

I am open to submitting a fix. I have had a similar issue in the 2.0 Beta version

**Comment by malikdev13** [comment] 2023-03-08 02:15
Hello, does this issue already have the solution ? bcs I still have this error, I am using 2.0.5

![image](https://user-images.githubusercontent.com/115519313/223601729-9dd07ec4-5907-469f-93a8-733b74044967.png)

**Comment by w4ll3** [comment] 2023-03-08 02:21
This is not a bug, it's the expected behavior. To improve security SIWE enforces EIP-55

**Comment by malikdev13** [comment] 2023-03-08 02:55
> This is not a bug, it's the expected behavior. To improve security SIWE enforces EIP-55

thanks for the response, so the passed address/signer address should be changed? I am using web3 onboard and after wallet connect, I just pass the response address

**Comment by w4ll3** [comment] 2023-03-08 03:02
yes, you probably want https://web3js.readthedocs.io/en/v1.2.11/web3-utils.html#tochecksumaddress

**Comment by obstropolos** [comment] 2023-03-14 18:49
Closing this for now - @malikdev13 please let us know if anything else comes up here.

**Closed by obstropolos** 2023-03-14 18:49 UTC
